language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '16.15.1'
install:
  - yarn install --ignore-engines
before_install:
  - npm i -g npm@^8.11.0
before_script:
  - npm prune
script:
  - npm run lint
after_success:
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
